# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vantran
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: user-service
# "service" is the name of this project. This will also be added to your AWS resource names.
service: user-service

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: app/handler.hello
    events:
      - httpApi:
          path: /
          method: get
plugins:
  - serverless-plugin-typescript
  - serverless-offline
